# Generated by Django 3.2 on 2023-02-21 20:50

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.RegexValidator(code='invalid_username', message='Username "me" not allowed!', regex='[^me$]')], verbose_name='Имя пользователя'),
        ),
    ]
