# Generated by Django 2.2.16 on 2023-02-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
        ('users', '0002_auto_20230222_1103'),
    ]

    operations = [
    ]
